### PR TITLE
Added vim shortcuts

### PR DESCRIPTION
**Pull request by GabMus**
NOTE: I couldn't test this since I wasn't able to build foliate from source. See #7 for more details on this issue.

### CODE REVIEW

**Comment by johnfactotum** [comment]
I'm not entirely sure if Vim shortcuts are appropriate for GTK applications. Vim shortcuts are more suitable for the CLI or apps that have complex editing/navigating capacities. It'd be better to stick to standard GTK or desktop style shortcuts, in my opinion.

**Comment by GabMus** [comment]
I'm pretty sure there are some gtk apps that implement vim shortcuts.
Besides, my PR doesn't remove existing shortcuts :)

**Comment by GabMus** [comment]
#7 closed, I was able to test the changes I made, and everything seems to be in order

**Comment by GabMus** [comment]
I'm not sure if it's appropriate to write it here, but I wanted to thank you for the amazing work that you're doing on Foliate, keep it up!

**Comment by johnfactotum** [comment]
I've made the shortcuts more consistent with Evince with fc30c1cc4744158fbc7f14b74106119aa6b822cd, this includes n and p for turning pages, and j and k for scrolling in scrolled mode. And also fixed the problem with space conflicting with scroll down in scrolled mode.

So I'll be closing this PR. Thank you for your contribution.

**Comment by GabMus** [comment]
I see that in 305ac2d64e566cfee3c1f52008f42bbeb894a890 you added all the vim shortcuts I implemented, namely `H` for left, `L` for right and `/` for search. They do not show up in the shortcuts tho. Just out of curiosity, what made you change your mind about them?

**Comment by johnfactotum** [comment]
I mentioned it in my comment above:

>  I've made the shortcuts more consistent with Evince...

Them not showing up in the shortcuts window is also in line with Evince. Also in general the shortcuts window has limited space, and it's best not to flood it with too many shortcuts. As mentioned in the [GTK3 Reference Manual](https://developer.gnome.org/gtk3/stable/GtkShortcutsShortcut.html):

> Multiple accelerators can be specified by separating them with a space, but keep in mind that the available width is limited.

**Comment by GabMus** [comment]
I personally think they should be there since they're implemented, but 
that's more of a GTK problem than Foliate's. At the end of the day, 
choice is yours. Thanks for implementing them anyway :)

**Comment by johnfactotum** [comment]
Thanks for the suggestion. I think I'll leave them out for now..

**Pull request closed without merging**
