### PR TITLE
updated to latest commit of gtk4 branch

### PR DESCRIPTION
**Pull request by soumyaDghosh**
This is also using webkitgtk-6, but it's in beta and supports only amd64 for now.

### CODE REVIEW

**Comment by johnfactotum** [comment]
The binary name is now `foliate`. Also there's no TTS support, so espeak, etc. is unused at the moment. The plan was to talk to host speech-dispatcher through socket. Alternatively it might use WebKitGTK's speech synthesis API. At any rate it doesn't and probably won't run espeak directly.

**Comment by soumyaDghosh** [comment]
Does foliate uses portals?

**Comment by johnfactotum** [comment]
If you mean when opening files, yes. GTK uses portals automatically.

**Comment by soumyaDghosh** [comment]
Then, no use of `home` and `removable-media`

**Comment by soumyaDghosh** [comment]
Any thoughts on merging this?

**Comment by johnfactotum** [comment]
Well, if you're sure that v2.6.4 stable works and won't need to be updated anymore, I guess. Or is there a way to maintain both versions?

**Comment by soumyaDghosh** [comment]
One single snap can do the trick, v2.6.4 is only need to updated if you make changes there.

**Comment by soumyaDghosh** [comment]
Seems like, it doesn't builds, when done from snap-store. Fixing it. Sorry about that typo.

**Pull request merged**
