### PR TITLE
Open with external application

### PR DESCRIPTION
**Pull request by axlEscalada**
- add functionality to open files with an external application

related to: https://github.com/johnfactotum/foliate/issues/1343

### CODE REVIEW

**Comment by johnfactotum** [comment]
Thanks! Can you make it follow the project's coding style, 4 spaces and no semicolons?

**Comment by axlEscalada** [comment]
> Thanks! Can you make it follow the project's coding style, 4 spaces and no semicolons?

It's done.
Btw I love foliate <3

**Comment by johnfactotum** [comment]
Thanks. The indentation is still incorrect, though. You can see this if you run `npx eslint`.

**Comment by axlEscalada** [comment]
> Thanks. The indentation is still incorrect, though. You can see this if you run `npx eslint`.

thanks for the hint, I ran `npx eslint --fix` to fix the format

**Pull request merged**
