### PR TITLE
[WIP] Add touch event handler

### PR DESCRIPTION
**Pull request by tokyovigilante**
Regarding #224, it seems that touch events are being sent as scroll wheel events. Nothing wrong with this specifically, although it would be better if WebKitGTK supported W3C pointer events, but this seems to be blocked on Apple not supporting it outside iOS Safari.

Anyway, WebKitGTK does support the older Touch Events API, so I've added this basic handler to epub.js to handle touch swipes. Annoyingly, the event handler uses a debounce to prevent scrolling multiple pages at a time seemingly, so I've had to add the `touchStarted` boolean to the `rendition` object. Apparently otherwise the `preventDefault()` calls are enough to block double-actions from both wheel and touch events. I didn't invent JS...

Annoyingly, this only seems to work currently with forward swipes. The `touchend` event is not called on a swipe backward, and I get the old behaviour of two page scrolling. One step forward and two steps back it seems. I'm not sure why this is as even the `rendition.prev()` function doesn't seem to be called, suggesting it isn't scroll wheel events either, maybe something to do with WebKitGTK enabling back and forward navigation on swipe in some cases (although this is opt-in and doesn't seem to be enabled).

This works well enough for me on forward swipe so I thought I'd post it up for comment. I don't know if it would be accepted upstream because ideally pointer events would be targeted for other browsers, but the code is modified from [upstream](https://github.com/futurepress/epub.js/wiki/Tips-and-Tricks-%28v0.3%29#swipe-to-turn-pages-with-touchevents), so once we get it working well I can try to push it there.

### CODE REVIEW

**Comment by johnfactotum** [comment]
Thanks for working on this. I think we should investigate what exactly is causing it to skip pages. Is it indeed a bug with the `onwheel` function? If not, perhaps one can try [Epub.js's example pages](https://futurepress.github.io/epub.js/examples/) and see if the issue occur there as well.

**Comment by tokyovigilante** [comment]
Hi John, thanks for the look. Sorry I didn't realise until reviewing the commit history today that epub-viewer.js is your code and not upstream. The epub.js viewer doesn't seem to have any mouse wheel or touch handling so I'm not sure they'll help us. 

The other thing I noticed is that the upstream viewer seems to have significantly better page-turning performance, and there is at least one un-necessary paint (and probably two) in profiling during page turns. I wonder if this can be improved? The trade off of course is that Foliate is SO. MUCH. PRETTIER. ;)

**Comment by jhakonen** [comment]
I stumbled on this PR as I was trying to figure out why Foliate was infrequently flipping 2 pages at same time when I was swiping the reader. It seems to me that this PR partially fixes that bad behaviour for me.

By adding some `console.log()` calls to the event handlers, I noticed that the `touchstart` event only triggers if the swipe starts at left or right edge of Foliate's window. The event is not triggered if the swipe starts from window's center.

Even though the touch event handlers are attached to the top level `document`, a touch event starting within the viewer element (perhaps because it is a iframe?) doesn't seem to be getting caught by the event handlers. 

With that observation, I created another set of `touchstart` and `touchend` handlers, with exactly the same content as the top level handlers, but attached them to `contents.document` instead. This seems to have fixed the swiping so that I'm not getting extra page flips any more when the swipe doesn't start from the edge.

Is checking of the `vr` check necessary? I seemed to have some difficulties getting my swipes horizontal enough for the page flip to trigger. Removing the vertical check made the swiping easier for me.

**Comment by jhakonen** [comment]
Here's my changes: https://gist.github.com/jhakonen/27a06112087a99512ceb3b952f52cc21

**Comment by johnfactotum** [comment]
@jhakonen Can you make a PR for your changes based on the latest master? `src/assets/epub-viewer.js` was moved to `src/web/epub-viewer.js`.

**Comment by jhakonen** [comment]
It turned out that the way the swipe is detected was still somewhat hard to use. You have to drag your finger across the screen for  25% width of the screen for the swipe to be detected.
There is however a class in Gtk that already implements swipe gesture detection: [Gtk.GestureSwipe](https://gjs-docs.gnome.org/gtk30~3.24.22/gtk.gestureswipe)
With that class, instead of dragging your finger across the screen, you only need the swipe your finger fast enough for the gesture to be detected. This way you do not need move your hand at all, as just a fast swipe of a finger is enough.
I've rewritten the touch handling using Gtk.GestureSwipe and I would like to make a PR out of that instead.

**Comment by johnfactotum** [comment]
Closing this now that #591 is merged

**Pull request closed without merging**
