### PR TITLE
Add Void Linux instructions to Readme

### PR DESCRIPTION
**Pull request by not-chicken**
While building package, gjs wasn't listed as runtime dependency so users have to install it alongside for the time being.

I will fix this in next revision of the package, and will open a PR to remove gjs from instructions.

### CODE REVIEW

**Comment by johnfactotum** [comment]
Thanks a lot for this!

Will it take long to fix the package? If not, I think I'll merge this after it's fixed.

**Comment by not-chicken** [comment]
Thanks to you for creating foliate :+1: , I just packaged it( that too with this little issue).

I was thinking of fixing it along with next update, or a week later. It just got added to repos so I don't want to ping void maintainers so soon.

My vote would be to merge this for the time being. Decision's up to you.

**Comment by johnfactotum** [comment]
Fair enough. I'd appreciate it if you could add an explanation to this in the readme, though, if this is to be merged now. I mean just to provide a slight reminder that `gjs` is a dependency and not something to be explicitly installed.

In fact, does Void Linux's package manager support installing a package as a dependency? If so it might be better to instruct people to do that.

If all this would be too verbose than I think I'd merge after it's fixed.

**Comment by not-chicken** [comment]
I have added a separate note for gjs. Later on we would just have to delete this note.

**Pull request merged**
