### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by johnfactotum** [comment]
Can you update the translations with the latest POT file?

**Comment by Vistaus** [comment]
I already did, and the strings I now translated are the ones Poeditor showed as new. I updated the fork an hour ago, so the POT file is up-to-date.

**Comment by johnfactotum** [comment]
But it's missing a lot of new strings. The POT creation date here is ` 2020-06-19 01:42+0800`. It should be `2020-07-02 14:22+0800`.

**Comment by Vistaus** [comment]
Strange. Seems like GitHub had some issues (also noticed a few other oddities on the site). I now see a newer POT file. I'll translate the new strings now :)

**Comment by Vistaus** [comment]
Alright, should be good to go now :)

**Comment by johnfactotum** [comment]
Thanks!

**Pull request merged**
