### PR TITLE
Add timestamp to annotation

### PR DESCRIPTION
**Pull request by azzamsa**
Hi.

It is a working implementation, but still very rough. I am ready to take any guidance to polish this PR further.

image

Fixes: #1048

### CODE REVIEW

**Comment by johnfactotum** [comment]
- Ideally it should probably have both `created` and `modified` instead of a single timestamp.
- The date should be saved as an ISO string.
- The displayed date should use the user's locale setting. See `src/format.js`.
- Opening the annotation popover should not change the date. A new date should be created when modifying the annotation.
- It might be better to display the dates in the popover instead of the sidebar.

**Comment by azzamsa** [comment]
I would like to separate this into two commits. 1) Storing to the JSON file 2) display in pop-over. I would like to ask your opinion on the first one. If it's okay, then I will start working on the second step.

**Comment by azzamsa** [comment]
It is very hard for me do debug because the right click is not reliable.

```
(com.github.johnfactotum.Foliate:11213): Gtk-CRITICAL **: 23:02:55.082: _gtk_css_corner_value_get_y: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed

(com.github.johnfactotum.Foliate:12531): Gtk-WARNING **: 23:06:20.941: gtk_widget_size_allocate(): attempt to allocate FoliateBookItem box 0x55a
9d5bd50e0 with width -30 and height -18

(WebKitWebProcess:2): GStreamer-WARNING **: 16:06:30.247: External plugin loader failed. This most likely means that the plugin loader helper bi
nary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should
normally not be required though.
```

Every time I add a new annotation the app freeze. I need to restart every time I want to debug.

```
OS: Fedora Linux 38 (Container Image) x86_64
Kernel: 6.3.8-200.fc38.x86_64
Shell: zsh 5.9
DE: GNOME
WM: Mutter
```

```
⬢ ❯ dnf list installed | grep gtk4
gtk4.x86_64                                 4.10.4-1.fc38                      @updates
javascriptcoregtk4.0.x86_64                 2.40.2-1.fc38                      @updates
javascriptcoregtk4.0-devel.x86_64           2.40.2-1.fc38                      @updates
webkit2gtk4.0.x86_64                        2.40.2-1.fc38                      @updates
webkit2gtk4.0-devel.x86_64                  2.40.2-1.fc38                      @updates

⬢ ❯ dnf list installed | grep webkit
webkit2gtk4.0.x86_64                        2.40.2-1.fc38                      @updates
webkit2gtk4.0-devel.x86_64                  2.40.2-1.fc38                      @updates
webkitgtk6.0.x86_64                         2.40.2-1.fc38                      @updates

⬢ ❯ dnf list installed | grep libadwaita
libadwaita.x86_64                           1.3.3-1.fc38                       @updates

⬢ ❯ gjs --version
gjs 1.76.2
```

**Comment by johnfactotum** [comment]
A new popover is created each time you click on an existing annotation. So the created date should not be set in the popover's constructor.  It should be set when creating the annotation. And new timestamps should be created when modifying the annotation.

> It is very hard for me do debug because the right click is not reliable.

There's no right click action anywhere in the app, though. Well, except for built-in context menu for GtkEntry and GtkTextView.

> Every time I add a new annotation the app freeze.

Can't reproduce this. It works fine for me.

**Comment by johnfactotum** [comment]
So I've went ahead and added this myself. Still thinking about how to present it in the UI.

**Pull request closed without merging**
