### PR TITLE
Added .deb producing script for ninja

### PR DESCRIPTION
**Pull request by itprojects**
Added the script package.deb.bin.sh to be run on demand with ninja like this:

ninja debian-bin

It will make foliate_x.y-z.deb file in build folder.

### CODE REVIEW

**Comment by johnfactotum** [comment]
1. The part after the dash of the version is `debian_revision`, and it "specifies the version of the Debian package based on the upstream version". 1.3.1 should become 1.3.1-1 or similar, not 1.3-1
2. Like I said in #44, redoing everything that's currently done by Meson by hand is unsatisfactory. Maybe use `meson build --prefix=$fnamefull/usr` instead of using `cp` to install things.

**Comment by itprojects** [comment]
1. Fixed the version numbers to just be 1.3.1 format, and not 1.3-1.
2. Yes, it's not satisfactory to copy by hand. On the other hand if the alternative is no package, that's a pool of millions of people that can enjoy your app. Especially for the main linux distributions Ubuntu/Debian/Elementary. Some will no doubt be dedicated maintainers and maybe after the first few .deb's they'll help package it on launchpad or similar. You've got to start somewhere!

**Comment by johnfactotum** [comment]
I've added the specification (e75f79e964c7d637374c3122b01a669bbd376f76). Debian packages can be built using the `dpkg-buildpackage` command.

**Comment by itprojects** [comment]
Thanks, this works.

**Pull request closed without merging**
