### PR TITLE
Add Python 3 compatibility to mobiml2xhtml.py

### PR DESCRIPTION
**Pull request by dfandrich**
Also, simplified a few constructs.

It runs in both Python 2 and Python 3 on some simple files but I haven't
performed thorough testing.

### CODE REVIEW

**Comment by johnfactotum** [comment]
Thanks! Can you make a pull request [upstream](https://github.com/kevinhendricks/KindleUnpack)?

**Comment by dfandrich** [comment]
Sure. What's upstream for this?

**Comment by johnfactotum** [comment]
https://github.com/kevinhendricks/KindleUnpack

**Comment by dfandrich** [comment]
https://github.com/kevinhendricks/KindleUnpack/pull/32

**Comment by dfandrich** [comment]
It's been merged upstream.

**Pull request merged**
