### PR TITLE
added Debian build dependencies

### PR DESCRIPTION
**Pull request by archisman-panigrahi**
I added the necessary build dependencies so that it builds, and also uploaded packages to the Launchpad PPA (for Ubuntu 23.10 and 24.04), which are building right now.

### CODE REVIEW

**Comment by johnfactotum** [comment]
TBH I don't understand why these are necessary.

Is `desktop-file-utils` just for running the post install `update_desktop_database` thing? But isn't Meson supposed to skip that when building debs?

**Comment by archisman-panigrahi** [comment]
Without `desktop-file-utils`, the Launchpad build failed with the meson error 
```
ERROR: Program 'update-desktop-database' not found or not executable
```
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1022550 I found that adding `desktop-file-utils` fixes this issue.

Also, meson fails to compile the debian package without the `-dev` packages for gtk4, libadwaita and gjs, and libwebkitgtk-6.0.

**Comment by johnfactotum** [comment]
> Also, meson fails to compile the debian package without the `-dev` packages for gtk4, libadwaita and gjs, and libwebkitgtk-6.0.

Ah yes, I think that's probably due to the dependency checks in 6148752efeda58a759a30214c7eb5b73841fd8ea?

> Without `desktop-file-utils`, the Launchpad build failed with the meson error

Yeah, and that looks like a Meson and/or dpkg bug to me. IIUC, the post install script is supposed to run only when installing, not when building a package.

**Comment by archisman-panigrahi** [comment]
> Ah yes, I think that's probably due to the dependency checks in [6148752](https://github.com/johnfactotum/foliate/commit/6148752efeda58a759a30214c7eb5b73841fd8ea)?

Yes, I think so.

> Yeah, and that looks like a Meson and/or dpkg bug to me. IIUC, the post install script is supposed to run only when installing, not when building a package.

I don't know much about this to have an opinion, but could be a bug.

**Comment by johnfactotum** [comment]
From https://mesonbuild.com/Gnome-module.html:

>  If `DESTDIR` is specified during installation all scripts will be skipped.

So probably for whatever reason, `DESTDIR` is no longer set when building debs. It surely worked before for Foliate v2.0, which has a post install script that checks for `DESTDIR` as well: https://github.com/johnfactotum/foliate/blob/master/build-aux/meson/postinstall.py. And it worked; you didn't have to install `desktop-file-utils`.

**Pull request merged**
